name: my_workflow.yml

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm my_workflow

    - name: Archive my_workflow reports
      uses: actions/upload-artifact@v2
      with:
        name: my_workflow
        path: https://github.com/kiran-kaler/demo-repo/edit/main/.github/my_workflow.yml
