name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Build Script
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          # Windows-specific commands
          echo "Running on Windows"
        else
          # Linux-specific commands
          echo "Running on Linux"
        fi


