name: My Workflow

on:
  push:
    branches:
      - main

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Workflow-Level Variable
        run: echo "Workflow-level variable value: ${{ env.MY_WORKFLOW_VARIABLE }}"

